platforma:
    host: ""
    username: ""
    password: ""
    api_version: v1.3

platformb:
    platformburl: "d"
    platformbresourceserverclientid: "a"
    platformbresourceserversecret: "d"
    platformbcorrugateclientcolonsecret: "a"
    platformbcorrugatesecret: "d"
    platformbcorrugateclient: "d"
    platformbhypervisorid: "d"
    platformbcluster: "a"
    platformbbrickhousetier: "d"
    platformbnetcidr: "d"
    platformbgatewayip: "a"
    platformbentityarid: "d"

